sprint0/sprint0/Game1.cs, sprint0/sprint0/HUD/HUDFactory.cs, sprint0/sprint0/HUD/HeartHUD.cs, sprint0/sprint0/Input/EnemyNPCNextSpriteCommand.cs, sprint0/sprint0/Input/EnemyNPCPreviousSpriteCommand.cs, sprint0/sprint0/Input/ItemNextSpriteCommand.cs, sprint0/sprint0/Input/ItemPreviousSpriteCommand.cs, sprint0/sprint0/Input/KeyboardController.cs, sprint0/sprint0/NPCs/Flame.cs
- Added item controller (i for next item, u for previous item)
- Added enemy/npc controller (p for next item, o for previous)
- have not added bosses yet
- adjusted location of hearts in HUD
- animated the flame
- adjusted locations of items so they're all in one line
- Adjusted locations of enemy/npc so they're all in one line
- Added old man 1, old man 2, old woman, and merchant (3) sprites to enemy/npc controller
=> Item, Enemy/NPC Controls, animated flame

sprint0/sprint0/Bosses/Dodongo/Dodongo.cs, sprint0/sprint0/Dungeon/Block.cs, sprint0/sprint0/Dungeon/Brick.cs, sprint0/sprint0/Dungeon/DungeonFactory.cs, sprint0/sprint0/Dungeon/Gap.cs, sprint0/sprint0/Dungeon/Ladder.cs, sprint0/sprint0/Dungeon/RoomBorder.cs, sprint0/sprint0/Dungeon/Stairs.cs, sprint0/sprint0/Dungeon/Tile.cs, sprint0/sprint0/Dungeon/Water.cs, sprint0/sprint0/Enemies/EnemiesSpriteFactory.cs, sprint0/sprint0/Enemies/Gel.cs, sprint0/sprint0/Enemies/Snake.cs, sprint0/sprint0/Enemies/Zol.cs, sprint0/sprint0/Game1.cs, sprint0/sprint0/Input/Command/ResetCommand.cs, sprint0/sprint0/Input/Command/RoomElementNextSpriteCommand.cs, sprint0/sprint0/Input/Command/RoomElementPreviousSpriteCommand.cs, sprint0/sprint0/Items/Bomb.cs, sprint0/sprint0/Items/Clock.cs, sprint0/sprint0/Items/Fairy.cs, sprint0/sprint0/NPCs/Flame.cs, sprint0/sprint0/NPCs/NpcsSpriteFactory.cs, sprint0/sprint0/Weapons/ItemsWeaponsSpriteFactory.cs
added fairy movement, no idea if what fairy is supposed to do b/c could not find in walkthrough
added author tags
=> Han branch6

sprint0/sprint0/Enemies/Wallmaster.cs, sprint0/sprint0/Game1.cs
- moves wallmaster in random directions
- added static variable for map size, and hud height (to determine which direction wallmaster is coming from)
=> wallmaster move

sprint0/sprint0/Game1.cs, sprint0/sprint0/Input/Command/OneCommand.cs, sprint0/sprint0/Input/Command/ThreeCommand.cs, sprint0/sprint0/Input/Command/TwoCommand.cs, sprint0/sprint0/Input/Controller/KeyboardController.cs, sprint0/sprint0/Items/Arrow.cs, sprint0/sprint0/Link/DamagedLink.cs, sprint0/sprint0/Link/IPlayer.cs, sprint0/sprint0/Link/Link.cs, sprint0/sprint0/Link/States/DownIdleState.cs, sprint0/sprint0/Link/States/IPlayerState.cs, sprint0/sprint0/Weapons/ItemsWeaponsSpriteFactory.cs
As a result of the funky way we're rendering weapons right now[one at a time...] it's impractical to actually render the fired arrows.
=> Added functionality to fire arrows

sprint0/sprint0/Dungeon/DungeonSprites.cs, sprint0/sprint0/Enemies/EnemyNPCSprites.cs, sprint0/sprint0/Enemies/Stalfos.cs, sprint0/sprint0/Enemies/Trap.cs, sprint0/sprint0/HUD/BombHUD.cs, sprint0/sprint0/HUD/HUD.cs, sprint0/sprint0/HUD/HUDFactory.cs, sprint0/sprint0/HUD/HUDItemA.cs, sprint0/sprint0/HUD/HUDItemB.cs, sprint0/sprint0/HUD/HeartHUD.cs, sprint0/sprint0/HUD/KeyHUD.cs, sprint0/sprint0/HUD/RupeeHUD.cs, sprint0/sprint0/Input/Command/EnemyNPCNextSpriteCommand.cs, sprint0/sprint0/Input/Command/EnemyNPCPreviousSpriteCommand.cs, sprint0/sprint0/Input/Command/ItemNextSpriteCommand.cs, sprint0/sprint0/Input/Command/ItemPreviousSpriteCommand.cs, sprint0/sprint0/Items/Compass.cs, sprint0/sprint0/Items/Key.cs, sprint0/sprint0/Items/Rupee.cs
added author tag and comments to classes I did and updated the Stalfos animation logic (it was on an old version for some reason). also removed the two useless methods at the bottom of DungeonSprites and made a few vars readonly
=> added author tag, comments, and updated stalfos animation

sprint0/sprint0/Game1.cs, sprint0/sprint0/Input/Command/ResetCommand.cs
* ResetCommand.cs: changed to just call game1's reset method
=> * Game1.cs: added resetGame method

sprint0/sprint0/Bosses/Dodongo/Dodongo.cs, sprint0/sprint0/Enemies/EnemyNPCSprites.cs, sprint0/sprint0/Enemies/Gel.cs, sprint0/sprint0/Enemies/Goriya.cs, sprint0/sprint0/Enemies/GoriyaBoomerang.cs, sprint0/sprint0/Enemies/Keese.cs, sprint0/sprint0/Enemies/Snake.cs, sprint0/sprint0/Enemies/Stalfos.cs, sprint0/sprint0/Enemies/Wallmaster.cs, sprint0/sprint0/Enemies/Zol.cs
enemies no longer go off screen
=> fix off screen for enemies

sprint0/sprint0/Dungeon/DungeonSprites.cs, sprint0/sprint0/Enemies/Zol.cs, sprint0/sprint0/Game1.cs, sprint0/sprint0/Items/Bomb.cs, sprint0/sprint0/Items/Fairy.cs, sprint0/sprint0/Link/Link.cs, sprint0/sprint0/Weapons/ItemsWeaponsSpriteFactory.cs
=> Han branch7

sprint0/sprint0/Enemies/EnemiesSpriteFactory.cs, sprint0/sprint0/Enemies/Wallmaster.cs, sprint0/sprint0/Game1.cs, sprint0/sprint0/Items/Boomerang.cs, sprint0/sprint0/Weapons/ItemsWeaponsSpriteFactory.cs
=> boomerang texture

sprint0/sprint0/Items/Arrow.cs, sprint0/sprint0/Items/Bomb.cs, sprint0/sprint0/Items/Bow.cs
Fixed rendering offsets for arrow and bomb.
=> Weapons offsets

sprint0/sprint0/Game1.cs, sprint0/sprint0/Input/Command/NextRoomCommand.cs, sprint0/sprint0/Input/Command/PreviousRoomCommand.cs, sprint0/sprint0/Input/Controller/KeyboardController.cs, sprint0/sprint0/LoadLevel/LevelLoader.cs, sprint0/sprint0/sprint0.csproj
- added functionality (COMMENTED OUT RN) to switch between room. 
- x = previous room, c = next room (COMMENTED OUT). 
- Since all xml files aren't created yet, switching to rooms 1 and 3-8 will cause an exception
=> switching from room to room (not map)

sprint0/sprint0/Content/LevelData/Room1.xml, sprint0/sprint0/Content/LevelData/Room10.xml, sprint0/sprint0/Content/LevelData/Room11.xml, sprint0/sprint0/Content/LevelData/Room12.xml, sprint0/sprint0/Content/LevelData/Room13.xml, sprint0/sprint0/Content/LevelData/Room14.xml, sprint0/sprint0/Content/LevelData/Room15.xml, sprint0/sprint0/Content/LevelData/Room16.xml, sprint0/sprint0/Content/LevelData/Room17.xml, sprint0/sprint0/Content/LevelData/Room2.xml, sprint0/sprint0/Content/LevelData/Room3.xml, sprint0/sprint0/Content/LevelData/Room4.xml, sprint0/sprint0/Content/LevelData/Room5.xml, sprint0/sprint0/Content/LevelData/Room6.xml, sprint0/sprint0/Content/LevelData/Room7.xml, sprint0/sprint0/Content/LevelData/Room8.xml, sprint0/sprint0/Content/LevelData/Room9.xml, sprint0/sprint0/LoadLevel/LevelLoader.cs
added rooms 1-9, 4 is basically not done
=> Hansp3 branch4

sprint0/sprint0/Content/LevelData/Room0.xml, sprint0/sprint0/Content/LevelData/Room4.xml, sprint0/sprint0/Content/LevelData/Room9.xml, sprint0/sprint0/Dungeon/Darkness.cs, sprint0/sprint0/Dungeon/DungeonFactory.cs, sprint0/sprint0/Game1.cs, sprint0/sprint0/Input/Command/NextRoomCommand.cs, sprint0/sprint0/Input/Command/PreviousRoomCommand.cs, sprint0/sprint0/LoadLevel/LevelLoader.cs, sprint0/sprint0/NPCs/Text.cs
added room 0 and room 4 plus text in game class(not elegant)
=> Hansp3 branch5

sprint0/sprint0/Game1.cs, sprint0/sprint0/Items/Arrow.cs, sprint0/sprint0/Link/DamagedLink.cs, sprint0/sprint0/Link/IPlayer.cs, sprint0/sprint0/Link/Link.cs, sprint0/sprint0/Link/Sprites/LeftWoodSwordSprite.cs, sprint0/sprint0/Link/Sprites/UpWoodSwordSprite.cs
Fixed a bajillion bugs:
- Added health and inventory for link
- Link has 16 health, each hit takes away half a heart(half a health)
- Added appropriate methods to receive items
- Fixed projectile rendering on water maps
- Added limited health to link
- Fixed rendering of sword beam
- Fixed sword attack up
- Fixed offsets of link's projectiles
- Sword beam now only goes when link is at full health
- Other minor issues
=> Bug buster

sprint0/sprint0/Bosses/Aquamentus/Aquamentus.cs, sprint0/sprint0/Bosses/Digdogger/Digdogger.cs, sprint0/sprint0/Bosses/Dodongo/Dodongo.cs, sprint0/sprint0/Bosses/Ganon/Ganon.cs, sprint0/sprint0/Bosses/Ganon/GanonFireball.cs, sprint0/sprint0/Bosses/Gleeok/Gleeok.cs, sprint0/sprint0/Bosses/Gleeok/GleeokHead.cs, sprint0/sprint0/Bosses/Gleeok/GleeokNeck.cs, sprint0/sprint0/Bosses/Gohma/Gohma.cs, sprint0/sprint0/Bosses/Manhandla/Manhandla.cs, sprint0/sprint0/Bosses/Manhandla/ManhandlaLimb.cs, sprint0/sprint0/Bosses/Patra/Patra.cs, sprint0/sprint0/Bosses/Patra/PatraMinion.cs, sprint0/sprint0/Collision/AllCollisionHandler.cs, sprint0/sprint0/Collision/EnemyBlockCollisionHandler.cs, sprint0/sprint0/Collision/EnemyEnemyCollisionHandler.cs, sprint0/sprint0/Collision/LinkBlockCollisionHandler.cs, sprint0/sprint0/Enemies/Gel.cs, sprint0/sprint0/Enemies/Goriya.cs, sprint0/sprint0/Enemies/Keese.cs, sprint0/sprint0/Enemies/Snake.cs, sprint0/sprint0/Enemies/Stalfos.cs, sprint0/sprint0/Enemies/Trap.cs, sprint0/sprint0/Enemies/Wallmaster.cs, sprint0/sprint0/Enemies/Zol.cs, sprint0/sprint0/Game1.cs, sprint0/sprint0/IEnemy.cs
- enemies change direction upon collision
- movable block gets pushed upon collision
- enemies collide with each other
- commented out ganon fireballs (scaled up)
- BUG: zol collision is weird
=> Collision6

sprint0/sprint0/Collision/AllCollisionHandler.cs, sprint0/sprint0/Collision/BlockBlockCollisionHandler.cs, sprint0/sprint0/Content/LevelData/Room1.xml, sprint0/sprint0/Content/LevelData/Room8.xml, sprint0/sprint0/Enemies/Gel.cs, sprint0/sprint0/Enemies/Trap.cs, sprint0/sprint0/Items/Fairy.cs, sprint0/sprint0/sprint0.csproj
added trap movement- for now only moves up because collision with room border should make it go down
added fairy- has bugs with collision
added block collision- has bug when link goes inside movable block
fixed xml files for room 8 and room 1
randomized gel movement
=> Hansp3 branch6

sprint0/sprint0/Collision/AllCollisionHandler.cs, sprint0/sprint0/Collision/LinkBlockCollisionHandler.cs, sprint0/sprint0/LoadLevel/LevelLoader.cs, sprint0/sprint0/NPCs/Flame.cs, sprint0/sprint0/NPCs/Merchant.cs, sprint0/sprint0/NPCs/NpcsSpriteFactory.cs, sprint0/sprint0/NPCs/OldPerson.cs
npcs literally are blocks in terms of conflict
=> npcs are blocks

sprint0/sprint0/Bosses/Gohma/Gohma.cs, sprint0/sprint0/Input/Controller/Gamepad.cs
removed damageCommand from gamepad, scaled up crab legs, and changed order of drawing so legs are drawn before head
=> removed damageCommand from gamepad and fixed crab

sprint0/sprint0/Bosses/Aquamentus/Aquamentus.cs, sprint0/sprint0/Bosses/Gleeok/Gleeok.cs, sprint0/sprint0/Bosses/Gohma/Gohma.cs, sprint0/sprint0/Bosses/Manhandla/Manhandla.cs, sprint0/sprint0/Bosses/Manhandla/ManhandlaLimb.cs, sprint0/sprint0/Bosses/Patra/Patra.cs
* Patra.cs:
* Gleeok.cs:
* Aquamentus.cs: added chechHealth to update
* Manhandla.cs: tried to do damage taking logic, but did not work
* ManhandlaLimb.cs: tried to do daamage taking logic but did not work
=> added checkHealth to most updates

sprint0/sprint0/Bosses/Ganon/Ganon.cs, sprint0/sprint0/Enemies/Snake.cs, sprint0/sprint0/Enemies/Wallmaster.cs
* Ganon.cs:
* Snake.cs: deleted unsed comments
=> * Wallmaster.cs: fixed wall master

sprint0/sprint0/Content/LevelData/Room0.xml, sprint0/sprint0/Content/LevelData/Room1.xml, sprint0/sprint0/Content/LevelData/Room10.xml, sprint0/sprint0/Content/LevelData/Room13.xml, sprint0/sprint0/Content/LevelData/Room15.xml, sprint0/sprint0/Content/LevelData/Room2.xml, sprint0/sprint0/Content/LevelData/Room3.xml, sprint0/sprint0/Content/LevelData/Room7.xml, sprint0/sprint0/Content/LevelData/Room8.xml, sprint0/sprint0/Content/LevelData/Room9.xml, sprint0/sprint0/Content/LevelData/RoomInvisible.xml, sprint0/sprint0/LoadLevel/LevelLoader.cs, sprint0/sprint0/Weapons/ItemsWeaponsSpriteFactory.cs
itemsWeapons in xml renamed to Items. LevelLoader no longer has projectile option. Items in xml files don't have dir or lifespan. currently working on invis blocks. updated room 7 boomerang pos
=> xml and level loader updates

sprint0/sprint0/Bosses/Aquamentus/Aquamentus.cs, sprint0/sprint0/Content/LevelData/Room8.xml
* Room8.xml: chnaged position of aquamentus to avoid collision
=> fixed aquamentus by moving his position (note aquamentus collision still bad)

sprint0/sprint0/Bosses/Manhandla/Manhandla.cs, sprint0/sprint0/Bosses/Manhandla/ManhandlaLimb.cs, sprint0/sprint0/Collision/EnemyWeaponCollisionHandler.cs, sprint0/sprint0/Game1.cs
* ManhandlaLimb.cs: d=tried to mak elimb die
* EnemyWeaponCollisionHandler.cs: made it so that emeies cannot kill
eachother
* Game1.cs: add registerEnemies
=> tried to make manhandala die-still does not work

sprint0/sprint0/Collision/LinkProjectileCollisionHandler.cs, sprint0/sprint0/Input/Command/FourCommand.cs, sprint0/sprint0/Input/Controller/KeyboardController.cs, sprint0/sprint0/Items/ArrowItem.cs, sprint0/sprint0/Items/BombItem.cs, sprint0/sprint0/Link/DamagedLink.cs, sprint0/sprint0/Link/IPlayer.cs, sprint0/sprint0/Link/Link.cs, sprint0/sprint0/Weapons/Boomerang.cs, sprint0/sprint0/Weapons/FlameProjectile.cs, sprint0/sprint0/Weapons/ItemsSpriteFactory.cs, sprint0/sprint0/Weapons/ProjectileSpriteFactory.cs, sprint0/sprint0/Weapons/WeaponsSpriteFactory.cs
=> Added bomb pickups, arrow pickups, and candle functionality

sprint0/sprint0/Content/LevelData/RoomInvisible.xml, sprint0/sprint0/LoadLevel/LevelLoader.cs
Made levelLoader shorter. Took out border blocks method. Added said blocks to RoomInvisible.xml. I haven't managed to do the big blocks yet, but this seems to work for now.
=> shortened levelloader. added invis blocks

sprint0/sprint0/Content/LevelData/Room1.xml, sprint0/sprint0/Enemies/Enemy.cs, sprint0/sprint0/Enemies/Gel.cs, sprint0/sprint0/Enemies/Snake.cs, sprint0/sprint0/Enemies/Trap.cs, sprint0/sprint0/Enemies/Trapparatus.cs, sprint0/sprint0/Enemies/Wallmaster.cs, sprint0/sprint0/Enemies/Zol.cs, sprint0/sprint0/Game1.cs, sprint0/sprint0/Link/Link.cs, sprint0/sprint0/Room.cs, sprint0/sprint0/Weapons/Boomerang.cs
- some enemies shorter
- boomerang shorter
=> Refactors3

sprint0/sprint0/Collision/LinkItemCollisionHandler.cs, sprint0/sprint0/Content/LevelData/Room1.xml, sprint0/sprint0/Game1.cs, sprint0/sprint0/HUD/BombHUD.cs, sprint0/sprint0/HUD/HUD.cs, sprint0/sprint0/HUD/HUDFactory.cs, sprint0/sprint0/HUD/HUDItemA.cs, sprint0/sprint0/HUD/HUDItemB.cs, sprint0/sprint0/HUD/HeartHUD.cs, sprint0/sprint0/HUD/KeyHUD.cs, sprint0/sprint0/HUD/MainHUD.cs, sprint0/sprint0/HUD/ManageHUDInventory.cs, sprint0/sprint0/HUD/PopulateHUDInventory.cs, sprint0/sprint0/HUD/RupeeHUD.cs, sprint0/sprint0/Interfaces/IHUD.cs, sprint0/sprint0/Interfaces/IHUDInventory.cs, sprint0/sprint0/Items/BombItem.cs, sprint0/sprint0/Items/Key.cs, sprint0/sprint0/Items/Rupee.cs, sprint0/sprint0/Link/DamagedLink.cs, sprint0/sprint0/Link/Link.cs, sprint0/sprint0/Link/LinkDamageControl.cs, sprint0/sprint0/Link/LinkUseItemHelper.cs, sprint0/sprint0/Room.cs
1. link doesn't spawn in the middle of the traps in room 1
2. huge HUD update (below are general notes. there are smaller changes/new files as well that contribute to the stuff below)
a. reduction of magic numbers/strings in factory and classes
b. hud now has 2 interfaces: one for the items with numbers (bomb, rupee, key, life) and one for the a/b slots and the general hud
c. link now takes damage 
d. if link walks into a key(item) the number in the hud goes up
NOTE: health and item counts reset everytime link switches a room; need to fix that for sprint 4
3. changed some of the references to Game1 to Room instead. This has only been in the following classes:
a. Link
b. DamagedLink
c. LinkUseItemHelper
=> STUTI HUD POWER

sprint0/sprint0/HUD/HeartHUD.cs, sprint0/sprint0/LoadLevel/LevelLoader.cs
made a couple of strings in levelloader a readonly string. also fixed bug of the number of hearts printed on the hud increasing after links death. added method for when link's health is 0
=> made some strings in levelloader a readonly string. fixed a heart bug on hud

sprint0/sprint0/Bosses/Manhandla/Manhandla.cs, sprint0/sprint0/Bosses/Manhandla/ManhandlaLimb.cs, sprint0/sprint0/Items/Fairy.cs, sprint0/sprint0/Weapons/ItemsSpriteFactory.cs
made fairy catchable and made manhandala get more powerful as dies
=> Hansp4 branch1

sprint0/sprint0/Collision/LinkItemCollisionHandler.cs, sprint0/sprint0/Content/LevelData/Room0.xml, sprint0/sprint0/Content/LevelData/Room13.xml, sprint0/sprint0/Content/LevelData/Room4.xml, sprint0/sprint0/Content/LevelData/Room8.xml, sprint0/sprint0/Content/LevelData/Room9.xml, sprint0/sprint0/HUD/BombHUD.cs, sprint0/sprint0/HUD/HUDManager.cs, sprint0/sprint0/HUD/HeartHUD.cs, sprint0/sprint0/HUD/KeyHUD.cs, sprint0/sprint0/HUD/PopulateHUDInventory.cs, sprint0/sprint0/HUD/RupeeHUD.cs, sprint0/sprint0/Interfaces/IHUDInventory.cs, sprint0/sprint0/Items/ItemsSpriteFactory.cs, sprint0/sprint0/Items/MagicalKey.cs, sprint0/sprint0/Items/MagicalRod.cs, sprint0/sprint0/Items/MagicalSword.cs, sprint0/sprint0/Items/WhiteSword.cs, sprint0/sprint0/Items/WoodenSword.cs, sprint0/sprint0/Link/Link.cs
- added sword classes and other items (magical rod, magical key, magical sword, white sword, wooden sword)
- fixed linkItemCollision readability
- added heart container functionality
- added property to IHUDInventory items to get the number
- TO DO: fix incrementing/picking up items for damaged link
- TO DO: make heart background in HUD black
=> added sword classes

sprint0/sprint0/Collision/LinkItemCollisionHandler.cs, sprint0/sprint0/Game1.cs, sprint0/sprint0/HUD/HUD.cs, sprint0/sprint0/HUD/HUDFactory.cs, sprint0/sprint0/HUD/HUDInventory.cs, sprint0/sprint0/HUD/HUDManager.cs, sprint0/sprint0/HUD/MainHUD.cs, sprint0/sprint0/HUD/PauseScreen.cs, sprint0/sprint0/HUD/PauseScreenManager.cs, sprint0/sprint0/Input/Command/PauseCommand.cs, sprint0/sprint0/Input/Controller/KeyboardController.cs, sprint0/sprint0/Link/DamagedLink.cs, sprint0/sprint0/Link/IPlayer.cs, sprint0/sprint0/Link/Link.cs
- inventory/pause screen
- press 'E' to open inventory/pause and press 'E' to close the inventory/unpause
- TO DO: still need to do map stuff and item selection
- TO DO: need to turn background on more HUD stuff black
- TO DO: still need to add item adding/setting functionality to damaged link
- TO DO: add 100+ item count functionality to HUD
=> inventory stuff

sprint0/sprint0/Bosses/Patra/Patra.cs, sprint0/sprint0/Bosses/Patra/PatraMinion.cs, sprint0/sprint0/Collision/EnemyBlockCollisionHandler.cs, sprint0/sprint0/Collision/EnemyEnemyCollisionHandler.cs, sprint0/sprint0/Collision/LinkEnemyCollisionHandler.cs
fixed Patra (have to kill minions first) and made link not walk through enemies
=> Hansp4 brach5

sprint0/sprint0/Bosses/Aquamentus/Aquamentus.cs, sprint0/sprint0/Bosses/Digdogger/Digdogger.cs, sprint0/sprint0/Bosses/Dodongo/Dodongo.cs, sprint0/sprint0/Bosses/Ganon/Ganon.cs, sprint0/sprint0/Bosses/Gleeok/Gleeok.cs, sprint0/sprint0/Bosses/Gohma/Gohma.cs, sprint0/sprint0/Bosses/Manhandla/Manhandla.cs, sprint0/sprint0/Bosses/Patra/Patra.cs, sprint0/sprint0/Enemies/Enemy.cs, sprint0/sprint0/Items/ItemSpawner.cs, sprint0/sprint0/RoomLoader/LoadLevel.cs, sprint0/sprint0/RoomLoader/RoomItems.cs, sprint0/sprint0/Weapons/Boomerang.cs
* ItemSpawner.cs:
* Enemy.cs:
* Ganon.cs:
* Patra.cs:
* Gleeok.cs:
* RoomItems.cs:
* Dodongo.cs:
* Digdogger.cs:
* Manhandla.cs:
* Aquamentus.cs: added spawn item
* Gohma.cs: add spawn item
* LoadLevel.cs: i cant remember
* Boomerang.cs: nothing
=> added item spawner

sprint0/sprint0/Content/LevelData/Room10.xml, sprint0/sprint0/Content/LevelData/Room2.xml, sprint0/sprint0/Content/LevelData/Room3.xml, sprint0/sprint0/Items/ItemSpawner.cs, sprint0/sprint0/RoomLoader/RoomEnemies.cs
* Room3.xml:
* Room10.xml: deleted key
* ItemSpawner.cs: added items for enemies to spawn
* RoomEnemies.cs: made keys and boomerang appear after all enemies
dead
=> made keys and boomerang spawn after all enemies died, added items for enemies to spawn

sprint0/sprint0/Link/DamagedLink.cs, sprint0/sprint0/Link/LinkUseItemHelper.cs, sprint0/sprint0/RoomLoader/LoadLevel.cs, sprint0/sprint0/RoomLoader/RoomMisc.cs, sprint0/sprint0/Weapons/Arrow.cs, sprint0/sprint0/Weapons/Boomerang.cs, sprint0/sprint0/Weapons/FlameProjectile.cs, sprint0/sprint0/Weapons/HitSprite.cs, sprint0/sprint0/Weapons/MiscSpriteFactory.cs, sprint0/sprint0/Weapons/ProjectileSpriteFactory.cs, sprint0/sprint0/Weapons/SwordBeam.cs, sprint0/sprint0/Weapons/SwordBeamExplode.cs, sprint0/sprint0/sprint0.csproj
Also fixed bug where boomerang wouldn't come back to Link and added damage to fire
=> Added projectile hit animation, refactored some projectile classes

sprint0/sprint0/Content/LevelData/Room10.xml, sprint0/sprint0/Content/LevelData/Room3.xml, sprint0/sprint0/Game1.cs, sprint0/sprint0/GameState/GameStateMachine.cs, sprint0/sprint0/HUD/HUDManager.cs, sprint0/sprint0/HUD/HUDMiniMap.cs, sprint0/sprint0/HUD/HUDMiniMapping.cs, sprint0/sprint0/Link/DamagedLink.cs, sprint0/sprint0/Link/Link.cs, sprint0/sprint0/Screen/Pause/PauseScreenMap.cs, sprint0/sprint0/UniversalScreenManager.cs
- moved one of the stalfos so link doesn't get damaged the second he teleports to the room
- removed 1/2 of the wall masters
- fixed play/test state bug
- items and health now reset
- universal screen manager (all screens but hud manager. adding hud manager causes errors)
- minor adjustment to draw location in hud map
=> enemy fix, state fix, resets, screen manager

sprint0/sprint0/Bosses/Aquamentus/Aquamentus.cs, sprint0/sprint0/Bosses/Digdogger/Digdogger.cs, sprint0/sprint0/Bosses/Dodongo/Dodongo.cs, sprint0/sprint0/Bosses/Ganon/Ganon.cs, sprint0/sprint0/Bosses/Gleeok/Gleeok.cs, sprint0/sprint0/Bosses/Gleeok/GleeokHead.cs, sprint0/sprint0/Bosses/Gleeok/GleeokNeck.cs, sprint0/sprint0/Bosses/Gleeok/GleeokNeckPiece.cs, sprint0/sprint0/Bosses/Gohma/Gohma.cs, sprint0/sprint0/Bosses/Manhandla/Manhandla.cs, sprint0/sprint0/Bosses/Manhandla/ManhandlaLimb.cs, sprint0/sprint0/Bosses/Patra/Patra.cs, sprint0/sprint0/Bosses/Patra/PatraMinion.cs, sprint0/sprint0/Collision/EnemyEnemyCollisionHandler.cs, sprint0/sprint0/Enemies/AbstractEnemy.cs, sprint0/sprint0/Enemies/Gel.cs, sprint0/sprint0/Enemies/Trapparatus.cs, sprint0/sprint0/Enemies/Zol.cs, sprint0/sprint0/GameState/GameStateMachine.cs, sprint0/sprint0/Interfaces/IEnemy.cs
- enemy and bosses have type property to neaten up enemyenemy collision handler (none, patra, manhandla, gel, or gleeok)
- link can now open pause menu in test mode
=> added enemy property. link can also open pause menu in test mode

sprint0/sprint0/AdjacentRooms.cs, sprint0/sprint0/Bosses/Digdogger/Digdogger.cs, sprint0/sprint0/Bosses/Ganon/Ganon.cs, sprint0/sprint0/Bosses/Gleeok/Gleeok.cs, sprint0/sprint0/Bosses/Gohma/Gohma.cs, sprint0/sprint0/Bosses/Manhandla/Manhandla.cs, sprint0/sprint0/Bosses/Patra/Patra.cs, sprint0/sprint0/Collision/AllCollisionHandler.cs, sprint0/sprint0/Collision/LinkBorderCollisionHandler.cs, sprint0/sprint0/Collision/LinkItemCollisionHandler.cs, sprint0/sprint0/Collision/LinkOverlayCollisionHandler.cs, sprint0/sprint0/Collision/WeaponBorderCollisionHandler.cs, sprint0/sprint0/Dungeon/BorderFilling/AbstractBorderFilling.cs, sprint0/sprint0/Dungeon/BorderFilling/LockedDoor.cs, sprint0/sprint0/Dungeon/BorderFilling/ShutDoor.cs, sprint0/sprint0/Dungeon/BorderFilling/Wall.cs, sprint0/sprint0/Dungeon/DungeonFactory.cs, sprint0/sprint0/Enemies/AbstractEnemy.cs, sprint0/sprint0/Enemies/DeathCloud.cs, sprint0/sprint0/Enemies/SpawnCloud.cs, sprint0/sprint0/LevelLoader.cs, sprint0/sprint0/Room.cs, sprint0/sprint0/RoomLoader/LoadLevel.cs, sprint0/sprint0/RoomLoader/RoomEffect.cs, sprint0/sprint0/RoomLoader/RoomSprite.cs, sprint0/sprint0/Weapons/Arrow.cs, sprint0/sprint0/Weapons/Boomerang.cs, sprint0/sprint0/Weapons/SwordBeam.cs
TODO check keys for opening doors
=> can open doors and bomb walls

sprint0/sprint0/Bosses/Ganon/Ganon.cs, sprint0/sprint0/Bosses/Ganon/GanonAshes.cs, sprint0/sprint0/Collision/LinkItemCollisionHandler.cs, sprint0/sprint0/Effects/EffectSpriteFactory.cs, sprint0/sprint0/Items/GanonTriforceAshes.cs, sprint0/sprint0/Items/ItemsSpriteFactory.cs
when go to triforce piece in ganon ashes, pick up animation for trifo…rce peice, ieffect for only ganon ashes
=> Triforce in Ganon Ashes

sprint0/sprint0/Collision/EnemyWeaponCollisionHandler.cs, sprint0/sprint0/Weapons/Boomerang.cs, sprint0/sprint0/Weapons/Sword.cs
Fixes bug where boomerang and sword were continuously hitting in 1 attack
=> Boomerang and Sword Enemy Collision

sprint0/sprint0/Enemies/AbstractEnemy.cs, sprint0/sprint0/Enemies/Goriya.cs, sprint0/sprint0/Weapons/Boomerang.cs
goriya boomerang not dying after goriya dies bug fixed
=> Goriya Boomerang Removal

sprint0/sprint0/Enemies/Trap.cs
traps move faster towards link and slower when returning
=> Trap Movement

sprint0/sprint0/Collision/BlockBlockCollisionHandler.cs, sprint0/sprint0/Collision/LinkBlockCollisionHandler.cs, sprint0/sprint0/Collision/LinkEnemyCollisionHandler.cs, sprint0/sprint0/Content/LevelData/Room5.xml, sprint0/sprint0/Dungeon/MovableBlock.cs, sprint0/sprint0/RoomLoader/RoomBlocks.cs, sprint0/sprint0/RoomLoader/RoomEnemies.cs
fix movable block mostly, fixed key spawning location, fixed bug where keys spawn before enemies dies because of spawn clouds, added offset to enemy link collision, made it so collision handler does not check movable block vs immovable block collision
=> Hansp4 branch8

sprint0/sprint0/Weapons/Arrow.cs
Arrow needs to be drawn with a different location rectangle than the rectangle that is used by the collision handler.
=> Arrow Hitbox

sprint0/sprint0/Collision/LinkBlockCollisionHandler.cs, sprint0/sprint0/Collision/LinkBorderCollisionHandler.cs, sprint0/sprint0/Content/LevelData/Room16.xml, sprint0/sprint0/Dungeon/BorderFilling/ShutDoor.cs, sprint0/sprint0/Dungeon/DungeonFactory.cs, sprint0/sprint0/Dungeon/Floor.cs, sprint0/sprint0/Dungeon/MovableBlock1.cs, sprint0/sprint0/Dungeon/MovableBlock5.cs, sprint0/sprint0/RoomLoader/RoomBlocks.cs, sprint0/sprint0/RoomLoader/RoomSprite.cs
=> Hansp4 branch9

sprint0/sprint0/Collision/AllCollisionHandler.cs, sprint0/sprint0/Collision/EnemyBorderCollisionHandler.cs
So enemies don't walk into doorways and also don't collide with link in the doorway and push him into another room.
=> EnemyBorderCollision

sprint0/sprint0/GameState/GameStateMachine.cs, sprint0/sprint0/LevelLoader.cs, sprint0/sprint0/RoomLoader/LoadLevel.cs
fixed link spawn location for when clicking thru
=> Link Spawn Location

sprint0/sprint0/Game1.cs, sprint0/sprint0/HUD/HUDMiniMapping.cs, sprint0/sprint0/Screen/Pause/PauseScreenMapping.cs
- room 18 now directly connects to room 1
- room 0 is no longer connected to room 18, it's only connected to room 1
- added functionality for rooms 19, 20, and 21 for when they're added
- added notes in the hud mini-map mapping and pause menu map mapping classes for what lines to remove/uncomment as rooms 19, 20, and 21 are added
- fixed issue of pause menu map not updating
=> fixed map. added functionality for rooms 19, 20, and 21

sprint0/sprint0/Collision/LinkBlockCollisionHandler.cs, sprint0/sprint0/Content/LevelData/Room19.xml, sprint0/sprint0/Content/LevelData/Room20.xml, sprint0/sprint0/Content/LevelData/Room21.xml, sprint0/sprint0/Dungeon/DungeonFactory.cs, sprint0/sprint0/Dungeon/SoundBlock.cs, sprint0/sprint0/Enemies/Owl.cs, sprint0/sprint0/LevelLoader.cs, sprint0/sprint0/Sound/SoundEffects/OwlSoundEffect.cs, sprint0/sprint0/Sound/SoundFactory.cs, sprint0/sprint0/Sound/SoundLoader.cs, sprint0/sprint0/Weapons/Fireball.cs
changed doors to open doors in rooms 19-21
=> Make owl shoot fireballs, added sound blocks,

sprint0/sprint0/Bosses/Digdogger/Digdogger.cs, sprint0/sprint0/HUD/HUDInventory.cs, sprint0/sprint0/HUD/HUDManager.cs, sprint0/sprint0/Input/Command/BItemCommand.cs, sprint0/sprint0/Input/Command/ChangeSwordCommand.cs, sprint0/sprint0/Input/Command/FluteCommand.cs, sprint0/sprint0/Input/Controller/KeyboardController.cs, sprint0/sprint0/RoomLoader/RoomEnemies.cs
- B is no longer used to use B items (just X)
- F is used to change swords
- using the flute while in the same room as the digdogger will make the digdogger small. this can't be reverted (ie the digdogger can't become big again after it's become small. this is intentional)
=> change sword using 'F', flute function

sprint0/sprint0/Input/Command/RodCommand.cs, sprint0/sprint0/Input/Command/SwordCommand.cs, sprint0/sprint0/Link/DamagedLink.cs, sprint0/sprint0/Link/IPlayer.cs, sprint0/sprint0/Link/Link.cs, sprint0/sprint0/Link/LinkUseItemHelper.cs, sprint0/sprint0/Link/States/DownIdleState.cs, sprint0/sprint0/Link/States/IPlayerState.cs, sprint0/sprint0/Link/States/LeftIdleState.cs, sprint0/sprint0/Link/States/RightIdleState.cs, sprint0/sprint0/Link/States/UpIdleState.cs
fixed magical rod bug where if you were holding a sword and had a magical rod, the sword would shoot out beams regardless of health
=> fixed one of the magical rod bugs

sprint0/sprint0/Input/Command/PotionCommand.cs, sprint0/sprint0/Items/StepLadder.cs
- potions (both kinds) get link back to full health
- fixed bug where ladder was drawn the wrong size in spider crab room
=> potions completely replenishes link's health

sprint0/sprint0/Content/LevelData/Room21.xml, sprint0/sprint0/Enemies/EnemiesSpriteFactory.cs, sprint0/sprint0/Enemies/FairyEnemy.cs, sprint0/sprint0/Input/Command/FairyEnlargementCommand.cs, sprint0/sprint0/Input/Controller/KeyboardController.cs, sprint0/sprint0/Input/Controller/SpecialControls/FairyEnlargementControl.cs, sprint0/sprint0/Items/FairyDistract.cs, sprint0/sprint0/Items/ItemSpawner.cs, sprint0/sprint0/Items/ItemsSpriteFactory.cs, sprint0/sprint0/Room.cs, sprint0/sprint0/RoomLoader/RoomEnemies.cs, sprint0/sprint0/Weapons/Fireball.cs
fixed east most peninsula text, made fairy room
=> Hansp5 branch8

sprint0/sprint0/Dungeon/AbstractBlock.cs, sprint0/sprint0/Dungeon/Block.cs, sprint0/sprint0/Dungeon/Brick.cs, sprint0/sprint0/Dungeon/Floor.cs, sprint0/sprint0/Dungeon/Gap.cs, sprint0/sprint0/Dungeon/Ladder.cs, sprint0/sprint0/Dungeon/MovableBlock1.cs, sprint0/sprint0/Dungeon/MovableBlock5.cs, sprint0/sprint0/Dungeon/SoundBlock.cs, sprint0/sprint0/Dungeon/Stairs.cs, sprint0/sprint0/Dungeon/Statue.cs, sprint0/sprint0/Dungeon/Tile.cs, sprint0/sprint0/Dungeon/Water.cs, sprint0/sprint0/HUD/HUDInventory.cs, sprint0/sprint0/HUD/HUDManager.cs, sprint0/sprint0/Input/Command/FourCommand.cs, sprint0/sprint0/Input/Command/Note1Command.cs, sprint0/sprint0/Input/Command/Note2Command.cs, sprint0/sprint0/Input/Command/Note3Command.cs, sprint0/sprint0/Input/Command/Note4Command.cs, sprint0/sprint0/Input/Command/Note5Command.cs, sprint0/sprint0/Input/Command/Note6Command.cs, sprint0/sprint0/Items/ArrowItem.cs, sprint0/sprint0/RoomLoader/RoomItems.cs
- abstract block
- fixed fairy bug where the game crashes if link tries to pick up a second fairy
=> abstract block, fairy bug fix

sprint0/sprint0/Collision/LinkBlockCollisionHandler.cs, sprint0/sprint0/Content/LevelData/Room1.xml, sprint0/sprint0/Content/LevelData/Room16.xml, sprint0/sprint0/Content/LevelData/Room17.xml, sprint0/sprint0/Content/LevelData/Room18.xml, sprint0/sprint0/Content/LevelData/Room19.xml, sprint0/sprint0/Content/LevelData/Room21.xml, sprint0/sprint0/Link/Link.cs, sprint0/sprint0/RoomLoader/RoomItems.cs
made fairy protect link for 3 hits, fixed link spawning position in room1
=> Hansp5 branch9

sprint0/sprint0/Bosses/Aquamentus/Aquamentus.cs, sprint0/sprint0/Bosses/Digdogger/Digdogger.cs, sprint0/sprint0/Bosses/Dodongo/Dodongo.cs, sprint0/sprint0/Bosses/Gleeok/Gleeok.cs, sprint0/sprint0/Bosses/Gohma/Gohma.cs, sprint0/sprint0/Bosses/Manhandla/Manhandla.cs, sprint0/sprint0/Bosses/Patra/Patra.cs, sprint0/sprint0/Enemies/FairyEnemy.cs, sprint0/sprint0/Enemies/Goriya.cs, sprint0/sprint0/Enemies/Owl.cs, sprint0/sprint0/Enemies/Snake.cs, sprint0/sprint0/Link/Link.cs, sprint0/sprint0/Weapons/Arrow.cs, sprint0/sprint0/Weapons/SwordBeam.cs
Added clock stopping to bosses
=> Refactored some enemies to use base.Update()

sprint0/sprint0/Dungeon/DarkRoom.cs
fixed bug where overlay would reappear once door was updated, also fixed bug where darkness would follow link into other rooms
=> Fixing Dark Room bugs

sprint0/sprint0/Enemies/Owl.cs, sprint0/sprint0/HUD/HUDInventory.cs, sprint0/sprint0/HUD/ItemSelection.cs, sprint0/sprint0/Screen/StartScreen/StartScreen.cs
- fixed bow/arrow thing
- adding thing to tell the user how to start playing in start mode
=> fixed bow/arrow thing
